module.exports = {
  company: {
    name: "NovaTech Solutions",
    founded: 2015,
    industry: "Tech / Software",
    headquarters: "San Francisco, CA",
    website: "www.novatechsolutions.com",
    employees_count: 250,
    revenue_usd: "45M",
  },

  departments: [
    {
      dept_id: "D001",
      name: "Engineering",
      head: "E003",
      budget_usd: 5000000,
      location: "Floor 3",
    },
    {
      dept_id: "D002",
      name: "Product Management",
      head: "E007",
      budget_usd: 2000000,
      location: "Floor 2",
    },
    {
      dept_id: "D003",
      name: "Sales",
      head: "E011",
      budget_usd: 3000000,
      location: "Floor 1",
    },
    {
      dept_id: "D004",
      name: "Marketing",
      head: "E014",
      budget_usd: 1500000,
      location: "Floor 2",
    },
    {
      dept_id: "D005",
      name: "Customer Success",
      head: "E017",
      budget_usd: 1200000,
      location: "Floor 1",
    },
    {
      dept_id: "D006",
      name: "HR & Operations",
      head: "E020",
      budget_usd: 900000,
      location: "Floor 4",
    },
  ],

  employees: [
    {
      emp_id: "E001",
      name: "Arjun Mehta",
      role: "Frontend Engineer",
      dept_id: "D001",
      email: "arjun.mehta@novatech.com",
      phone: "+1-415-555-0101",
      salary_usd: 120000,
      hire_date: "2020-03-15",
      status: "active",
    },
    {
      emp_id: "E002",
      name: "Priya Nair",
      role: "Backend Engineer",
      dept_id: "D001",
      email: "priya.nair@novatech.com",
      phone: "+1-415-555-0102",
      salary_usd: 125000,
      hire_date: "2019-07-22",
      status: "active",
    },
    {
      emp_id: "E003",
      name: "James Carter",
      role: "VP of Engineering",
      dept_id: "D001",
      email: "james.carter@novatech.com",
      phone: "+1-415-555-0103",
      salary_usd: 195000,
      hire_date: "2017-01-10",
      status: "active",
    },
    {
      emp_id: "E004",
      name: "Mei Lin",
      role: "DevOps Engineer",
      dept_id: "D001",
      email: "mei.lin@novatech.com",
      phone: "+1-415-555-0104",
      salary_usd: 130000,
      hire_date: "2021-05-01",
      status: "active",
    },
    {
      emp_id: "E005",
      name: "Rahul Sharma",
      role: "QA Engineer",
      dept_id: "D001",
      email: "rahul.sharma@novatech.com",
      phone: "+1-415-555-0105",
      salary_usd: 105000,
      hire_date: "2022-08-12",
      status: "active",
    },
    {
      emp_id: "E006",
      name: "Sofia Reyes",
      role: "ML Engineer",
      dept_id: "D001",
      email: "sofia.reyes@novatech.com",
      phone: "+1-415-555-0106",
      salary_usd: 140000,
      hire_date: "2020-11-30",
      status: "active",
    },
    {
      emp_id: "E007",
      name: "Daniel Park",
      role: "VP of Product",
      dept_id: "D002",
      email: "daniel.park@novatech.com",
      phone: "+1-415-555-0107",
      salary_usd: 180000,
      hire_date: "2018-04-18",
      status: "active",
    },
    {
      emp_id: "E008",
      name: "Ananya Iyer",
      role: "Product Manager",
      dept_id: "D002",
      email: "ananya.iyer@novatech.com",
      phone: "+1-415-555-0108",
      salary_usd: 135000,
      hire_date: "2021-02-25",
      status: "active",
    },
    {
      emp_id: "E009",
      name: "Tom Fischer",
      role: "UX Designer",
      dept_id: "D002",
      email: "tom.fischer@novatech.com",
      phone: "+1-415-555-0109",
      salary_usd: 115000,
      hire_date: "2022-01-17",
      status: "active",
    },
    {
      emp_id: "E010",
      name: "Keiko Tanaka",
      role: "Product Analyst",
      dept_id: "D002",
      email: "keiko.tanaka@novatech.com",
      phone: "+1-415-555-0110",
      salary_usd: 110000,
      hire_date: "2023-03-07",
      status: "active",
    },
    {
      emp_id: "E011",
      name: "Marcus Webb",
      role: "VP of Sales",
      dept_id: "D003",
      email: "marcus.webb@novatech.com",
      phone: "+1-415-555-0111",
      salary_usd: 175000,
      hire_date: "2016-09-01",
      status: "active",
    },
    {
      emp_id: "E012",
      name: "Fatima Al-Hassan",
      role: "Account Executive",
      dept_id: "D003",
      email: "fatima.alhassan@novatech.com",
      phone: "+1-415-555-0112",
      salary_usd: 95000,
      hire_date: "2021-06-14",
      status: "active",
    },
    {
      emp_id: "E013",
      name: "Luis Gomez",
      role: "Sales Development Rep",
      dept_id: "D003",
      email: "luis.gomez@novatech.com",
      phone: "+1-415-555-0113",
      salary_usd: 75000,
      hire_date: "2023-09-20",
      status: "active",
    },
    {
      emp_id: "E014",
      name: "Natasha Ivanova",
      role: "Head of Marketing",
      dept_id: "D004",
      email: "natasha.ivanova@novatech.com",
      phone: "+1-415-555-0114",
      salary_usd: 155000,
      hire_date: "2019-03-11",
      status: "active",
    },
    {
      emp_id: "E015",
      name: "Brian Okafor",
      role: "Content Strategist",
      dept_id: "D004",
      email: "brian.okafor@novatech.com",
      phone: "+1-415-555-0115",
      salary_usd: 90000,
      hire_date: "2022-07-05",
      status: "active",
    },
    {
      emp_id: "E016",
      name: "Claire Dubois",
      role: "Growth Marketer",
      dept_id: "D004",
      email: "claire.dubois@novatech.com",
      phone: "+1-415-555-0116",
      salary_usd: 98000,
      hire_date: "2021-10-19",
      status: "active",
    },
    {
      emp_id: "E017",
      name: "Vikram Patel",
      role: "Head of Customer Success",
      dept_id: "D005",
      email: "vikram.patel@novatech.com",
      phone: "+1-415-555-0117",
      salary_usd: 145000,
      hire_date: "2018-12-03",
      status: "active",
    },
    {
      emp_id: "E018",
      name: "Yuna Kim",
      role: "Customer Success Manager",
      dept_id: "D005",
      email: "yuna.kim@novatech.com",
      phone: "+1-415-555-0118",
      salary_usd: 100000,
      hire_date: "2022-04-28",
      status: "active",
    },
    {
      emp_id: "E019",
      name: "Ravi Chandran",
      role: "Support Engineer",
      dept_id: "D005",
      email: "ravi.chandran@novatech.com",
      phone: "+1-415-555-0119",
      salary_usd: 88000,
      hire_date: "2023-01-09",
      status: "active",
    },
    {
      emp_id: "E020",
      name: "Sandra Mills",
      role: "HR Director",
      dept_id: "D006",
      email: "sandra.mills@novatech.com",
      phone: "+1-415-555-0120",
      salary_usd: 150000,
      hire_date: "2017-06-15",
      status: "active",
    },
    {
      emp_id: "E021",
      name: "Ahmed Farouk",
      role: "Recruiter",
      dept_id: "D006",
      email: "ahmed.farouk@novatech.com",
      phone: "+1-415-555-0121",
      salary_usd: 80000,
      hire_date: "2022-11-01",
      status: "active",
    },
    {
      emp_id: "E022",
      name: "Leila Torres",
      role: "Operations Manager",
      dept_id: "D006",
      email: "leila.torres@novatech.com",
      phone: "+1-415-555-0122",
      salary_usd: 115000,
      hire_date: "2020-08-20",
      status: "on_leave",
    },
  ],

  products_services: [
    {
      product_id: "P001",
      name: "NovaCRM",
      type: "SaaS",
      category: "Customer Relationship Management",
      description:
        "AI-powered CRM platform for mid-market and enterprise teams.",
      pricing_model: "subscription",
      price_usd: { monthly: 99, annual: 999 },
      launched: "2018-06-01",
      status: "active",
      tech_stack: ["React", "Node.js", "PostgreSQL", "AWS"],
    },
    {
      product_id: "P002",
      name: "NovaAnalytics",
      type: "SaaS",
      category: "Business Intelligence",
      description: "Real-time data analytics and dashboard reporting tool.",
      pricing_model: "subscription",
      price_usd: { monthly: 149, annual: 1499 },
      launched: "2020-02-14",
      status: "active",
      tech_stack: ["Vue.js", "Python", "ClickHouse", "GCP"],
    },
    {
      product_id: "P003",
      name: "NovaSecure",
      type: "SaaS",
      category: "Cybersecurity",
      description: "Zero-trust security and access management for enterprises.",
      pricing_model: "subscription",
      price_usd: { monthly: 299, annual: 2999 },
      launched: "2022-09-01",
      status: "active",
      tech_stack: ["Go", "Kubernetes", "Azure", "Redis"],
    },
    {
      product_id: "P004",
      name: "NovaAPI Gateway",
      type: "PaaS",
      category: "Developer Tools",
      description:
        "Managed API gateway with rate limiting, auth, and monitoring.",
      pricing_model: "usage_based",
      price_usd: { per_million_requests: 5 },
      launched: "2021-05-20",
      status: "active",
      tech_stack: ["Rust", "Nginx", "AWS Lambda", "DynamoDB"],
    },
    {
      product_id: "P005",
      name: "Professional Services",
      type: "Service",
      category: "Consulting & Implementation",
      description: "Custom integrations, onboarding, and technical consulting.",
      pricing_model: "hourly",
      price_usd: { hourly_rate: 200 },
      launched: "2015-01-01",
      status: "active",
      tech_stack: [],
    },
  ],

  clients: [
    {
      client_id: "C001",
      company: "BrightPath Inc.",
      industry: "E-commerce",
      country: "USA",
      contact_name: "Jason Lee",
      contact_email: "jlee@brightpath.com",
      products_subscribed: ["P001", "P002"],
      account_value_usd: 48000,
      since: "2019-03-01",
      status: "active",
    },
    {
      client_id: "C002",
      company: "FinEdge Corp",
      industry: "Finance",
      country: "UK",
      contact_name: "Emily Watson",
      contact_email: "ewatson@finedge.co.uk",
      products_subscribed: ["P001", "P003"],
      account_value_usd: 130000,
      since: "2020-07-15",
      status: "active",
    },
    {
      client_id: "C003",
      company: "MediCore Systems",
      industry: "Healthcare",
      country: "Canada",
      contact_name: "Dr. Arun Bose",
      contact_email: "abose@medicore.ca",
      products_subscribed: ["P002", "P003"],
      account_value_usd: 95000,
      since: "2021-01-20",
      status: "active",
    },
    {
      client_id: "C004",
      company: "UrbanNest Realty",
      industry: "Real Estate",
      country: "USA",
      contact_name: "Stephanie Cruz",
      contact_email: "scruz@urbannest.com",
      products_subscribed: ["P001"],
      account_value_usd: 12000,
      since: "2022-05-10",
      status: "active",
    },
    {
      client_id: "C005",
      company: "SkyRoute Logistics",
      industry: "Logistics",
      country: "Australia",
      contact_name: "Chris Nguyen",
      contact_email: "cnguyen@skyroute.com.au",
      products_subscribed: ["P002", "P004"],
      account_value_usd: 62000,
      since: "2021-11-03",
      status: "active",
    },
    {
      client_id: "C006",
      company: "TerraGrow Agri",
      industry: "Agriculture Tech",
      country: "India",
      contact_name: "Pooja Rao",
      contact_email: "prao@terragrow.in",
      products_subscribed: ["P001", "P005"],
      account_value_usd: 35000,
      since: "2023-02-28",
      status: "active",
    },
    {
      client_id: "C007",
      company: "PulseMedia Group",
      industry: "Media & Publishing",
      country: "USA",
      contact_name: "Derek Sullivan",
      contact_email: "dsullivan@pulsemedia.com",
      products_subscribed: ["P002"],
      account_value_usd: 18000,
      since: "2022-09-14",
      status: "active",
    },
    {
      client_id: "C008",
      company: "OmniRetail Ltd.",
      industry: "Retail",
      country: "Germany",
      contact_name: "Hans Müller",
      contact_email: "hmuller@omniretail.de",
      products_subscribed: ["P001", "P002", "P003"],
      account_value_usd: 175000,
      since: "2020-03-22",
      status: "active",
    },
    {
      client_id: "C009",
      company: "Zephyr Cloud Co.",
      industry: "Cloud Services",
      country: "Singapore",
      contact_name: "Ling Wei",
      contact_email: "lwei@zephyrcloud.sg",
      products_subscribed: ["P003", "P004"],
      account_value_usd: 88000,
      since: "2022-12-01",
      status: "active",
    },
    {
      client_id: "C010",
      company: "NorthStar Edu",
      industry: "EdTech",
      country: "USA",
      contact_name: "Monica Hart",
      contact_email: "mhart@northstaredu.com",
      products_subscribed: ["P001"],
      account_value_usd: 11000,
      since: "2023-07-18",
      status: "churned",
    },
  ],
};
